// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyEa3odhids7FTxO_6lutEET0yItJi_c',
    appId: '1:15499243431:android:8f55e97c0a93fbc310d082',
    messagingSenderId: '15499243431',
    projectId: 'smenergy-14cc7',
    databaseURL: 'https://smenergy-14cc7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smenergy-14cc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ofKq6mUA7OjerSgkOGFcEX4-Ulbd4Zo',
    appId: '1:15499243431:ios:bc03054a700db38f10d082',
    messagingSenderId: '15499243431',
    projectId: 'smenergy-14cc7',
    databaseURL: 'https://smenergy-14cc7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smenergy-14cc7.firebasestorage.app',
    iosClientId: '15499243431-h6dbndk1153llnuvcjhuh13ntngussq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smenergy',
  );
}
