[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter =
    +<*>
    -<change_addr.cpp>
    -<pzem_sequence_test.cpp>

lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome @ ^2.1.4
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    mobizt/FirebaseClient
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9

[env:pzem_sequence_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter =
    -<*>
    +<pzem_sequence_test.cpp>

lib_deps =
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
